package org.miaoshaproject.dao;

import org.apache.ibatis.annotations.Param;
import org.miaoshaproject.dataobject.ItemDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 20 12:24:29 SGT 2021
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 20 12:24:29 SGT 2021
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 20 12:24:29 SGT 2021
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 20 12:24:29 SGT 2021
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 20 12:24:29 SGT 2021
     */
    int updateByPrimaryKey(ItemDO record);
    List<ItemDO> listItem();

    int increaseSales(@Param("id")Integer id,@Param("amount")Integer amount);
}